# Generated by Django 3.2.9 on 2021-11-18 17:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('count_of_students', models.IntegerField(default=0)),
            ],
        ),
    ]
