# Generated by Django 3.2.8 on 2021-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20211016_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='num_group',
            field=models.CharField(max_length=5),
        ),
    ]
