# Generated by Django 3.2.9 on 2021-11-18 18:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=120, null=True, unique=True, validators=[students.validators.no_elon_validator])),
                ('birthdate', models.DateField(default=datetime.date.today, null=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('summary', models.FileField(blank=True, null=True, upload_to='static/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
