# Generated by Django 3.2.8 on 2021-10-27 14:17

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211024_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True, validators=[students.validators.no_elon_validator]),
        ),
    ]
