# Generated by Django 3.2.8 on 2021-10-27 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password1",
            field=models.CharField(
                default="12345678",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="password2",
            field=models.CharField(
                default="12345678",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
