# Generated by Django 3.2.8 on 2021-10-27 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_auto_20211027_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password1",
            field=models.CharField(
                default="",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="password2",
            field=models.CharField(
                default="",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
