# Generated by Django 3.2.9 on 2021-11-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211027_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password2',
        ),
    ]
