# Generated by Django 3.2.9 on 2021-11-03 18:32

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20211103_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[students.validators.no_elon_validator]),
        ),
    ]
