# Generated by Django 3.2.9 on 2021-11-07 15:57

import datetime
import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_course_count_of_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=120, null=True, unique=True, validators=[students.validators.no_elon_validator])),
                ('birthdate', models.DateField(default=datetime.date.today, null=True)),
                ('course', models.ManyToManyField(to='students.Course')),
            ],
        ),
    ]
