# Generated by Django 3.2.8 on 2021-10-16 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
