# Generated by Django 3.2.8 on 2021-10-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_teachers_birthdate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teachers",
            new_name="Teacher",
        ),
    ]
