# Generated by Django 3.2.9 on 2021-11-18 17:58

import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0003_rename_teachers_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teachers', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True, validators=[students.validators.no_elon_validator]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
